name: Second WorkFlow

on: push

jobs:
    multiflow:
        runs-on: ubuntu-latest
        steps:
         - name: excueting the content of the shell scripts
           run: ./shellscript.sh